"""init_schema

Revision ID: d1f440167fdd
Revises: 
Create Date: 2026-10-05 18:57:47.702929

Not: Docker/Postgres olmayan ortamda bos SQLite semasina karsi autogenerate edildi;
SQLite dialect artiklari (Text() niteleyicisi, CURRENT_TIMESTAMP) Postgres kanonik bicime elle duzeltildi.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd1f440167fdd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corpus_authors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('openalex_id', sa.String(length=100), nullable=True),
    sa.Column('full_name', sa.String(length=500), nullable=True),
    sa.Column('orcid', sa.String(length=50), nullable=True),
    sa.Column('affiliation', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corpus_authors_openalex_id'), 'corpus_authors', ['openalex_id'], unique=True)
    op.create_table('journal_quartile_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('issn', sa.String(length=20), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('quartile', sa.String(length=5), nullable=True),
    sa.Column('sjr_score', sa.Float(), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('area_mapping', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issn', 'year', 'category', name='uq_journal_quartile_year_cat')
    )
    op.create_index(op.f('ix_journal_quartile_history_issn'), 'journal_quartile_history', ['issn'], unique=False)
    op.create_index(op.f('ix_journal_quartile_history_year'), 'journal_quartile_history', ['year'], unique=False)
    op.create_table('journals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('issn', sa.String(length=20), nullable=True),
    sa.Column('eissn', sa.String(length=20), nullable=True),
    sa.Column('quartile', sa.String(length=5), nullable=True),
    sa.Column('sjr_score', sa.Float(), nullable=True),
    sa.Column('h_index', sa.Integer(), nullable=True),
    sa.Column('total_cites_3y', sa.Integer(), nullable=True),
    sa.Column('field', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('is_turkey_journal', sa.Boolean(), nullable=False),
    sa.Column('openalex_id', sa.String(length=100), nullable=True),
    sa.Column('norm_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('institution', sa.String(length=255), nullable=True),
    sa.Column('primary_field', sa.String(length=100), nullable=True),
    sa.Column('academic_role', sa.String(length=100), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('subscription_tier', sa.String(length=50), nullable=False),
    sa.Column('subscription_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('orcid_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_size_kb', sa.Integer(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('detected_field', sa.String(length=100), nullable=True),
    sa.Column('selected_field', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('rejection_risk_score', sa.Float(), nullable=True),
    sa.Column('score_title', sa.Float(), nullable=True),
    sa.Column('score_abstract', sa.Float(), nullable=True),
    sa.Column('score_structure', sa.Float(), nullable=True),
    sa.Column('score_delivery', sa.Float(), nullable=True),
    sa.Column('score_lexical', sa.Float(), nullable=True),
    sa.Column('score_literature', sa.Float(), nullable=True),
    sa.Column('score_originality', sa.Float(), nullable=True),
    sa.Column('score_methodology', sa.Float(), nullable=True),
    sa.Column('score_findings', sa.Float(), nullable=True),
    sa.Column('score_conclusions', sa.Float(), nullable=True),
    sa.Column('score_references', sa.Float(), nullable=True),
    sa.Column('full_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('revision_suggestions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('journal_matches', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('corpus_works',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('openalex_id', sa.String(length=100), nullable=True),
    sa.Column('doi', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=1000), nullable=True),
    sa.Column('abstract', sa.String(), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('journal_id', sa.UUID(), nullable=True),
    sa.Column('journal_name', sa.String(length=500), nullable=True),
    sa.Column('journal_issn', sa.String(length=20), nullable=True),
    sa.Column('cited_by_count', sa.Integer(), nullable=True),
    sa.Column('is_oa', sa.Boolean(), nullable=False),
    sa.Column('oa_url', sa.String(length=1000), nullable=True),
    sa.Column('oa_license', sa.String(length=50), nullable=True),
    sa.Column('pdf_storage_key', sa.String(length=500), nullable=True),
    sa.Column('primary_area', sa.String(length=50), nullable=True),
    sa.Column('primary_subarea', sa.String(length=100), nullable=True),
    sa.Column('secondary_areas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('quartile_at_publication', sa.String(length=5), nullable=True),
    sa.Column('source_tier', sa.String(length=20), nullable=False),
    sa.Column('commercial_use_allowed', sa.Boolean(), nullable=False),
    sa.Column('consent_given', sa.Boolean(), nullable=False),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corpus_works_doi'), 'corpus_works', ['doi'], unique=True)
    op.create_index(op.f('ix_corpus_works_journal_issn'), 'corpus_works', ['journal_issn'], unique=False)
    op.create_index(op.f('ix_corpus_works_openalex_id'), 'corpus_works', ['openalex_id'], unique=True)
    op.create_index(op.f('ix_corpus_works_primary_area'), 'corpus_works', ['primary_area'], unique=False)
    op.create_index(op.f('ix_corpus_works_publication_year'), 'corpus_works', ['publication_year'], unique=False)
    op.create_index(op.f('ix_corpus_works_source_tier'), 'corpus_works', ['source_tier'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('plan', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thesis_projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('field', sa.String(length=100), nullable=True),
    sa.Column('target_journal', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analysis_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['thesis_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('corpus_work_authors',
    sa.Column('work_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['corpus_authors.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['corpus_works.id'], ),
    sa.PrimaryKeyConstraint('work_id', 'author_id')
    )
    op.create_table('usage_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('analysis_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usage_logs')
    op.drop_table('corpus_work_authors')
    op.drop_table('analysis_versions')
    op.drop_table('thesis_projects')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_corpus_works_source_tier'), table_name='corpus_works')
    op.drop_index(op.f('ix_corpus_works_publication_year'), table_name='corpus_works')
    op.drop_index(op.f('ix_corpus_works_primary_area'), table_name='corpus_works')
    op.drop_index(op.f('ix_corpus_works_openalex_id'), table_name='corpus_works')
    op.drop_index(op.f('ix_corpus_works_journal_issn'), table_name='corpus_works')
    op.drop_index(op.f('ix_corpus_works_doi'), table_name='corpus_works')
    op.drop_table('corpus_works')
    op.drop_table('analyses')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('journals')
    op.drop_index(op.f('ix_journal_quartile_history_year'), table_name='journal_quartile_history')
    op.drop_index(op.f('ix_journal_quartile_history_issn'), table_name='journal_quartile_history')
    op.drop_table('journal_quartile_history')
    op.drop_index(op.f('ix_corpus_authors_openalex_id'), table_name='corpus_authors')
    op.drop_table('corpus_authors')
    # ### end Alembic commands ###
